version: "3.9"
services:
    nginx:
      image: nginx:latest
      # build: ./nginx/
      container_name: nginx
      ports:
       - 80:80
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./php/:/var/www/html
      # depends_on:
      # - php

    php:
      build: ./php/
      expose:
        - 9000
      volumes:
        - ./php/:/var/www/html
    
    db:
      image: mysql:latest
      platform: linux/amd64
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: mydb
      volumes:
        - mysql-data:/var/lib/mysql
        - ./db-load-script.sql:/docker-entrypoint-initdb.d/db-load-script.sql

volumes:
    mysql-data: